Let bricked DTPF accept primitive blast furnace recipes, use screwdri…
Nxer/Twist-Space-Technology-Mod pull request #260
Opened 2024-02-26 11:20 UTC by koiNoCirculation

…ver to switch mode.
![2024-02-26_03 13 32](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/57739338/c759fad6-1104-493f-8ec7-90ff35374c83)

2024-02-26 11:23 UTC, Nxer commented
@HoleFish

2024-02-26 11:49 UTC, Nxer commented
How do the new normal primitive blast furnace do? Paralleled ? or something

2024-02-26 15:05 UTC, HoleFish requested changes

2024-02-26 15:05 UTC, HoleFish commented on src/main/java/com/Nxer/TwistSpaceTechnology/common/machine/GT_TileEntity_MegaBrickedBlastFurnace.java
> +    static class ItemWithDamage {
Use `GT_Utility.ItemId` or `TST_ItemID`

2024-02-26 15:05 UTC, HoleFish commented on src/main/java/com/Nxer/TwistSpaceTechnology/common/machine/GT_TileEntity_MegaBrickedBlastFurnace.java
> +    }
Useless

2024-02-26 15:05 UTC, HoleFish commented on src/main/java/com/Nxer/TwistSpaceTechnology/common/machine/GT_TileEntity_MegaBrickedBlastFurnace.java
> +                    count -= 64;
There's no 64 stacksize limit for output items list

2024-02-26 15:05 UTC, HoleFish commented on src/main/java/com/Nxer/TwistSpaceTechnology/common/machine/GT_TileEntity_MegaBrickedBlastFurnace.java
> +                consumeSize -= 64;
`input.stackSize` rather than 64 limits `consumeSize`

2024-02-26 15:05 UTC, HoleFish commented on src/main/java/com/Nxer/TwistSpaceTechnology/common/machine/GT_TileEntity_MegaBrickedBlastFurnace.java
> +            itemCountInput.put(itemWithDamage, itemCount);
Use `merge`

2024-02-26 19:32 UTC, koiNoCirculation commented on src/main/java/com/Nxer/TwistSpaceTechnology/common/machine/GT_TileEntity_MegaBrickedBlastFurnace.java
> +            itemCountInput.put(itemWithDamage, itemCount);
Well, ItemStack doesn't seem to have merge() method.

2024-02-27 02:34 UTC, HoleFish commented on src/main/java/com/Nxer/TwistSpaceTechnology/common/machine/GT_TileEntity_MegaBrickedBlastFurnace.java
> +            itemCountInput.put(itemWithDamage, itemCount);
`HashMap` does

2024-02-27 06:02 UTC, Nxer requested changes

2024-02-27 06:02 UTC, Nxer commented on src/main/java/com/Nxer/TwistSpaceTechnology/common/machine/GT_TileEntity_MegaBrickedBlastFurnace.java
> +import java.util.*;
Do not use the wildcard * , check your IDE settings.

2024-02-27 06:02 UTC, Nxer commented on src/main/java/com/Nxer/TwistSpaceTechnology/common/machine/GT_TileEntity_MegaBrickedBlastFurnace.java
>              itemCountInput.put(itemWithDamage, itemCount);
Turn to use `merge` , seems the final.

2024-02-28 04:01 UTC, Nxer approved these changes

2024-02-28 05:35 UTC, merged