fix IMM structure
Nxer/Twist-Space-Technology-Mod pull request #530
Opened 2024-07-12 10:55 UTC by YueLengM

2024-07-12 17:56 UTC, Nxer requested changes
You need to make a new structure definition and then replace the old one, and in `checkMachine` if the new structure check failed, check the old structure then let player's old machine doesn't be broken.

2024-07-12 17:57 UTC, Nxer commented
like this pr #511

2024-07-12 18:26 UTC, YueLengM commented
There are changes to `survivalConstruct` in #511, should I also apply it here?

2024-07-13 10:10 UTC, Nxer approved these changes

2024-07-13 12:38 UTC, merged